// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_server.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "client_server.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace packet_cs {

namespace {

const ::google::protobuf::Descriptor* MsgReqLoginCL_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgReqLoginCL_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgLoginResultLC_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgLoginResultLC_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgSelectServerCL_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgSelectServerCL_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgSeclectServerResultLC_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgSeclectServerResultLC_reflection_ = NULL;
const ::google::protobuf::Descriptor* MsgQuitLoginCL_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgQuitLoginCL_reflection_ = NULL;
const ::google::protobuf::Descriptor* PktGameLoginReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PktGameLoginReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* PktRoleListAck_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PktRoleListAck_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_client_5fserver_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_client_5fserver_2eproto() {
  protobuf_AddDesc_client_5fserver_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "client_server.proto");
  GOOGLE_CHECK(file != NULL);
  MsgReqLoginCL_descriptor_ = file->message_type(0);
  static const int MsgReqLoginCL_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgReqLoginCL, account_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgReqLoginCL, password_),
  };
  MsgReqLoginCL_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgReqLoginCL_descriptor_,
      MsgReqLoginCL::default_instance_,
      MsgReqLoginCL_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgReqLoginCL),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgReqLoginCL, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgReqLoginCL, _is_default_instance_));
  MsgLoginResultLC_descriptor_ = file->message_type(1);
  static const int MsgLoginResultLC_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLoginResultLC, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLoginResultLC, token_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLoginResultLC, servers_),
  };
  MsgLoginResultLC_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgLoginResultLC_descriptor_,
      MsgLoginResultLC::default_instance_,
      MsgLoginResultLC_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgLoginResultLC),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLoginResultLC, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLoginResultLC, _is_default_instance_));
  MsgSelectServerCL_descriptor_ = file->message_type(2);
  static const int MsgSelectServerCL_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSelectServerCL, server_id_),
  };
  MsgSelectServerCL_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgSelectServerCL_descriptor_,
      MsgSelectServerCL::default_instance_,
      MsgSelectServerCL_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgSelectServerCL),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSelectServerCL, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSelectServerCL, _is_default_instance_));
  MsgSeclectServerResultLC_descriptor_ = file->message_type(3);
  static const int MsgSeclectServerResultLC_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSeclectServerResultLC, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSeclectServerResultLC, gate_ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSeclectServerResultLC, gate_port_),
  };
  MsgSeclectServerResultLC_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgSeclectServerResultLC_descriptor_,
      MsgSeclectServerResultLC::default_instance_,
      MsgSeclectServerResultLC_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgSeclectServerResultLC),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSeclectServerResultLC, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgSeclectServerResultLC, _is_default_instance_));
  MsgQuitLoginCL_descriptor_ = file->message_type(4);
  static const int MsgQuitLoginCL_offsets_[1] = {
  };
  MsgQuitLoginCL_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MsgQuitLoginCL_descriptor_,
      MsgQuitLoginCL::default_instance_,
      MsgQuitLoginCL_offsets_,
      -1,
      -1,
      -1,
      sizeof(MsgQuitLoginCL),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgQuitLoginCL, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgQuitLoginCL, _is_default_instance_));
  PktGameLoginReq_descriptor_ = file->message_type(5);
  static const int PktGameLoginReq_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktGameLoginReq, account_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktGameLoginReq, session_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktGameLoginReq, ip_address_),
  };
  PktGameLoginReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PktGameLoginReq_descriptor_,
      PktGameLoginReq::default_instance_,
      PktGameLoginReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(PktGameLoginReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktGameLoginReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktGameLoginReq, _is_default_instance_));
  PktRoleListAck_descriptor_ = file->message_type(6);
  static const int PktRoleListAck_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktRoleListAck, role_name_list_),
  };
  PktRoleListAck_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PktRoleListAck_descriptor_,
      PktRoleListAck::default_instance_,
      PktRoleListAck_offsets_,
      -1,
      -1,
      -1,
      sizeof(PktRoleListAck),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktRoleListAck, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PktRoleListAck, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_client_5fserver_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgReqLoginCL_descriptor_, &MsgReqLoginCL::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgLoginResultLC_descriptor_, &MsgLoginResultLC::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgSelectServerCL_descriptor_, &MsgSelectServerCL::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgSeclectServerResultLC_descriptor_, &MsgSeclectServerResultLC::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MsgQuitLoginCL_descriptor_, &MsgQuitLoginCL::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PktGameLoginReq_descriptor_, &PktGameLoginReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PktRoleListAck_descriptor_, &PktRoleListAck::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_client_5fserver_2eproto() {
  delete MsgReqLoginCL::default_instance_;
  delete MsgReqLoginCL_reflection_;
  delete MsgLoginResultLC::default_instance_;
  delete MsgLoginResultLC_reflection_;
  delete MsgSelectServerCL::default_instance_;
  delete MsgSelectServerCL_reflection_;
  delete MsgSeclectServerResultLC::default_instance_;
  delete MsgSeclectServerResultLC_reflection_;
  delete MsgQuitLoginCL::default_instance_;
  delete MsgQuitLoginCL_reflection_;
  delete PktGameLoginReq::default_instance_;
  delete PktGameLoginReq_reflection_;
  delete PktRoleListAck::default_instance_;
  delete PktRoleListAck_reflection_;
}

void protobuf_AddDesc_client_5fserver_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_client_5fserver_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::pb_base::protobuf_AddDesc_base_5ftype_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023client_server.proto\022\tpacket_cs\032\017base_t"
    "ype.proto\"7\n\rMsgReqLoginCL\022\024\n\014account_na"
    "me\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"Z\n\020MsgLoginRe"
    "sultLC\022\016\n\006result\030\001 \001(\005\022\r\n\005token\030\002 \001(\t\022\'\n"
    "\007servers\030\003 \003(\0132\026.pb_base.ServerProfile\"&"
    "\n\021MsgSelectServerCL\022\021\n\tserver_id\030\001 \001(\005\"N"
    "\n\030MsgSeclectServerResultLC\022\016\n\006result\030\001 \001"
    "(\005\022\017\n\007gate_ip\030\002 \001(\t\022\021\n\tgate_port\030\003 \001(\005\"\020"
    "\n\016MsgQuitLoginCL\"P\n\017PktGameLoginReq\022\024\n\014a"
    "ccount_name\030\001 \001(\t\022\023\n\013session_key\030\002 \001(\t\022\022"
    "\n\nip_address\030\003 \001(\t\"(\n\016PktRoleListAck\022\026\n\016"
    "role_name_list\030\001 \003(\tb\006proto3", 468);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "client_server.proto", &protobuf_RegisterTypes);
  MsgReqLoginCL::default_instance_ = new MsgReqLoginCL();
  MsgLoginResultLC::default_instance_ = new MsgLoginResultLC();
  MsgSelectServerCL::default_instance_ = new MsgSelectServerCL();
  MsgSeclectServerResultLC::default_instance_ = new MsgSeclectServerResultLC();
  MsgQuitLoginCL::default_instance_ = new MsgQuitLoginCL();
  PktGameLoginReq::default_instance_ = new PktGameLoginReq();
  PktRoleListAck::default_instance_ = new PktRoleListAck();
  MsgReqLoginCL::default_instance_->InitAsDefaultInstance();
  MsgLoginResultLC::default_instance_->InitAsDefaultInstance();
  MsgSelectServerCL::default_instance_->InitAsDefaultInstance();
  MsgSeclectServerResultLC::default_instance_->InitAsDefaultInstance();
  MsgQuitLoginCL::default_instance_->InitAsDefaultInstance();
  PktGameLoginReq::default_instance_->InitAsDefaultInstance();
  PktRoleListAck::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_client_5fserver_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_client_5fserver_2eproto {
  StaticDescriptorInitializer_client_5fserver_2eproto() {
    protobuf_AddDesc_client_5fserver_2eproto();
  }
} static_descriptor_initializer_client_5fserver_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgReqLoginCL::kAccountNameFieldNumber;
const int MsgReqLoginCL::kPasswordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgReqLoginCL::MsgReqLoginCL()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet_cs.MsgReqLoginCL)
}

void MsgReqLoginCL::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgReqLoginCL::MsgReqLoginCL(const MsgReqLoginCL& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:packet_cs.MsgReqLoginCL)
}

void MsgReqLoginCL::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  account_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MsgReqLoginCL::~MsgReqLoginCL() {
  // @@protoc_insertion_point(destructor:packet_cs.MsgReqLoginCL)
  SharedDtor();
}

void MsgReqLoginCL::SharedDtor() {
  account_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MsgReqLoginCL::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgReqLoginCL::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgReqLoginCL_descriptor_;
}

const MsgReqLoginCL& MsgReqLoginCL::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_client_5fserver_2eproto();
  return *default_instance_;
}

MsgReqLoginCL* MsgReqLoginCL::default_instance_ = NULL;

MsgReqLoginCL* MsgReqLoginCL::New(::google::protobuf::Arena* arena) const {
  MsgReqLoginCL* n = new MsgReqLoginCL;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgReqLoginCL::Clear() {
// @@protoc_insertion_point(message_clear_start:packet_cs.MsgReqLoginCL)
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MsgReqLoginCL::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet_cs.MsgReqLoginCL)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string account_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account_name().data(), this->account_name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.MsgReqLoginCL.account_name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_password;
        break;
      }

      // optional string password = 2;
      case 2: {
        if (tag == 18) {
         parse_password:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), this->password().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.MsgReqLoginCL.password"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:packet_cs.MsgReqLoginCL)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet_cs.MsgReqLoginCL)
  return false;
#undef DO_
}

void MsgReqLoginCL::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet_cs.MsgReqLoginCL)
  // optional string account_name = 1;
  if (this->account_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account_name().data(), this->account_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgReqLoginCL.account_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->account_name(), output);
  }

  // optional string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgReqLoginCL.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->password(), output);
  }

  // @@protoc_insertion_point(serialize_end:packet_cs.MsgReqLoginCL)
}

::google::protobuf::uint8* MsgReqLoginCL::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet_cs.MsgReqLoginCL)
  // optional string account_name = 1;
  if (this->account_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account_name().data(), this->account_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgReqLoginCL.account_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->account_name(), target);
  }

  // optional string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgReqLoginCL.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->password(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:packet_cs.MsgReqLoginCL)
  return target;
}

int MsgReqLoginCL::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:packet_cs.MsgReqLoginCL)
  int total_size = 0;

  // optional string account_name = 1;
  if (this->account_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account_name());
  }

  // optional string password = 2;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgReqLoginCL::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet_cs.MsgReqLoginCL)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgReqLoginCL* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgReqLoginCL>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet_cs.MsgReqLoginCL)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet_cs.MsgReqLoginCL)
    MergeFrom(*source);
  }
}

void MsgReqLoginCL::MergeFrom(const MsgReqLoginCL& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet_cs.MsgReqLoginCL)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.account_name().size() > 0) {

    account_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_name_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
}

void MsgReqLoginCL::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet_cs.MsgReqLoginCL)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgReqLoginCL::CopyFrom(const MsgReqLoginCL& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet_cs.MsgReqLoginCL)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgReqLoginCL::IsInitialized() const {

  return true;
}

void MsgReqLoginCL::Swap(MsgReqLoginCL* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgReqLoginCL::InternalSwap(MsgReqLoginCL* other) {
  account_name_.Swap(&other->account_name_);
  password_.Swap(&other->password_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgReqLoginCL::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgReqLoginCL_descriptor_;
  metadata.reflection = MsgReqLoginCL_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgReqLoginCL

// optional string account_name = 1;
void MsgReqLoginCL::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgReqLoginCL::account_name() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgReqLoginCL.account_name)
  return account_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgReqLoginCL::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet_cs.MsgReqLoginCL.account_name)
}
 void MsgReqLoginCL::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet_cs.MsgReqLoginCL.account_name)
}
 void MsgReqLoginCL::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet_cs.MsgReqLoginCL.account_name)
}
 ::std::string* MsgReqLoginCL::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:packet_cs.MsgReqLoginCL.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgReqLoginCL::release_account_name() {
  // @@protoc_insertion_point(field_release:packet_cs.MsgReqLoginCL.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgReqLoginCL::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:packet_cs.MsgReqLoginCL.account_name)
}

// optional string password = 2;
void MsgReqLoginCL::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgReqLoginCL::password() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgReqLoginCL.password)
  return password_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgReqLoginCL::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet_cs.MsgReqLoginCL.password)
}
 void MsgReqLoginCL::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet_cs.MsgReqLoginCL.password)
}
 void MsgReqLoginCL::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet_cs.MsgReqLoginCL.password)
}
 ::std::string* MsgReqLoginCL::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:packet_cs.MsgReqLoginCL.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgReqLoginCL::release_password() {
  // @@protoc_insertion_point(field_release:packet_cs.MsgReqLoginCL.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgReqLoginCL::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:packet_cs.MsgReqLoginCL.password)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgLoginResultLC::kResultFieldNumber;
const int MsgLoginResultLC::kTokenFieldNumber;
const int MsgLoginResultLC::kServersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgLoginResultLC::MsgLoginResultLC()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet_cs.MsgLoginResultLC)
}

void MsgLoginResultLC::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgLoginResultLC::MsgLoginResultLC(const MsgLoginResultLC& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:packet_cs.MsgLoginResultLC)
}

void MsgLoginResultLC::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  result_ = 0;
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MsgLoginResultLC::~MsgLoginResultLC() {
  // @@protoc_insertion_point(destructor:packet_cs.MsgLoginResultLC)
  SharedDtor();
}

void MsgLoginResultLC::SharedDtor() {
  token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MsgLoginResultLC::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgLoginResultLC::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgLoginResultLC_descriptor_;
}

const MsgLoginResultLC& MsgLoginResultLC::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_client_5fserver_2eproto();
  return *default_instance_;
}

MsgLoginResultLC* MsgLoginResultLC::default_instance_ = NULL;

MsgLoginResultLC* MsgLoginResultLC::New(::google::protobuf::Arena* arena) const {
  MsgLoginResultLC* n = new MsgLoginResultLC;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgLoginResultLC::Clear() {
// @@protoc_insertion_point(message_clear_start:packet_cs.MsgLoginResultLC)
  result_ = 0;
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  servers_.Clear();
}

bool MsgLoginResultLC::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet_cs.MsgLoginResultLC)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 result = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_token;
        break;
      }

      // optional string token = 2;
      case 2: {
        if (tag == 18) {
         parse_token:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->token().data(), this->token().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.MsgLoginResultLC.token"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_servers;
        break;
      }

      // repeated .pb_base.ServerProfile servers = 3;
      case 3: {
        if (tag == 26) {
         parse_servers:
          DO_(input->IncrementRecursionDepth());
         parse_loop_servers:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_servers()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_servers;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:packet_cs.MsgLoginResultLC)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet_cs.MsgLoginResultLC)
  return false;
#undef DO_
}

void MsgLoginResultLC::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet_cs.MsgLoginResultLC)
  // optional int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // optional string token = 2;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgLoginResultLC.token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->token(), output);
  }

  // repeated .pb_base.ServerProfile servers = 3;
  for (unsigned int i = 0, n = this->servers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->servers(i), output);
  }

  // @@protoc_insertion_point(serialize_end:packet_cs.MsgLoginResultLC)
}

::google::protobuf::uint8* MsgLoginResultLC::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet_cs.MsgLoginResultLC)
  // optional int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // optional string token = 2;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgLoginResultLC.token");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->token(), target);
  }

  // repeated .pb_base.ServerProfile servers = 3;
  for (unsigned int i = 0, n = this->servers_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->servers(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:packet_cs.MsgLoginResultLC)
  return target;
}

int MsgLoginResultLC::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:packet_cs.MsgLoginResultLC)
  int total_size = 0;

  // optional int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  // optional string token = 2;
  if (this->token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->token());
  }

  // repeated .pb_base.ServerProfile servers = 3;
  total_size += 1 * this->servers_size();
  for (int i = 0; i < this->servers_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->servers(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgLoginResultLC::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet_cs.MsgLoginResultLC)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgLoginResultLC* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgLoginResultLC>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet_cs.MsgLoginResultLC)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet_cs.MsgLoginResultLC)
    MergeFrom(*source);
  }
}

void MsgLoginResultLC::MergeFrom(const MsgLoginResultLC& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet_cs.MsgLoginResultLC)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  servers_.MergeFrom(from.servers_);
  if (from.result() != 0) {
    set_result(from.result());
  }
  if (from.token().size() > 0) {

    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
}

void MsgLoginResultLC::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet_cs.MsgLoginResultLC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgLoginResultLC::CopyFrom(const MsgLoginResultLC& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet_cs.MsgLoginResultLC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgLoginResultLC::IsInitialized() const {

  return true;
}

void MsgLoginResultLC::Swap(MsgLoginResultLC* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgLoginResultLC::InternalSwap(MsgLoginResultLC* other) {
  std::swap(result_, other->result_);
  token_.Swap(&other->token_);
  servers_.UnsafeArenaSwap(&other->servers_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgLoginResultLC::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgLoginResultLC_descriptor_;
  metadata.reflection = MsgLoginResultLC_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgLoginResultLC

// optional int32 result = 1;
void MsgLoginResultLC::clear_result() {
  result_ = 0;
}
 ::google::protobuf::int32 MsgLoginResultLC::result() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgLoginResultLC.result)
  return result_;
}
 void MsgLoginResultLC::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:packet_cs.MsgLoginResultLC.result)
}

// optional string token = 2;
void MsgLoginResultLC::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgLoginResultLC::token() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgLoginResultLC.token)
  return token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgLoginResultLC::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet_cs.MsgLoginResultLC.token)
}
 void MsgLoginResultLC::set_token(const char* value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet_cs.MsgLoginResultLC.token)
}
 void MsgLoginResultLC::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet_cs.MsgLoginResultLC.token)
}
 ::std::string* MsgLoginResultLC::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:packet_cs.MsgLoginResultLC.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgLoginResultLC::release_token() {
  // @@protoc_insertion_point(field_release:packet_cs.MsgLoginResultLC.token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgLoginResultLC::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:packet_cs.MsgLoginResultLC.token)
}

// repeated .pb_base.ServerProfile servers = 3;
int MsgLoginResultLC::servers_size() const {
  return servers_.size();
}
void MsgLoginResultLC::clear_servers() {
  servers_.Clear();
}
const ::pb_base::ServerProfile& MsgLoginResultLC::servers(int index) const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgLoginResultLC.servers)
  return servers_.Get(index);
}
::pb_base::ServerProfile* MsgLoginResultLC::mutable_servers(int index) {
  // @@protoc_insertion_point(field_mutable:packet_cs.MsgLoginResultLC.servers)
  return servers_.Mutable(index);
}
::pb_base::ServerProfile* MsgLoginResultLC::add_servers() {
  // @@protoc_insertion_point(field_add:packet_cs.MsgLoginResultLC.servers)
  return servers_.Add();
}
::google::protobuf::RepeatedPtrField< ::pb_base::ServerProfile >*
MsgLoginResultLC::mutable_servers() {
  // @@protoc_insertion_point(field_mutable_list:packet_cs.MsgLoginResultLC.servers)
  return &servers_;
}
const ::google::protobuf::RepeatedPtrField< ::pb_base::ServerProfile >&
MsgLoginResultLC::servers() const {
  // @@protoc_insertion_point(field_list:packet_cs.MsgLoginResultLC.servers)
  return servers_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgSelectServerCL::kServerIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgSelectServerCL::MsgSelectServerCL()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet_cs.MsgSelectServerCL)
}

void MsgSelectServerCL::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgSelectServerCL::MsgSelectServerCL(const MsgSelectServerCL& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:packet_cs.MsgSelectServerCL)
}

void MsgSelectServerCL::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  server_id_ = 0;
}

MsgSelectServerCL::~MsgSelectServerCL() {
  // @@protoc_insertion_point(destructor:packet_cs.MsgSelectServerCL)
  SharedDtor();
}

void MsgSelectServerCL::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgSelectServerCL::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgSelectServerCL::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgSelectServerCL_descriptor_;
}

const MsgSelectServerCL& MsgSelectServerCL::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_client_5fserver_2eproto();
  return *default_instance_;
}

MsgSelectServerCL* MsgSelectServerCL::default_instance_ = NULL;

MsgSelectServerCL* MsgSelectServerCL::New(::google::protobuf::Arena* arena) const {
  MsgSelectServerCL* n = new MsgSelectServerCL;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgSelectServerCL::Clear() {
// @@protoc_insertion_point(message_clear_start:packet_cs.MsgSelectServerCL)
  server_id_ = 0;
}

bool MsgSelectServerCL::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet_cs.MsgSelectServerCL)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 server_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &server_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:packet_cs.MsgSelectServerCL)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet_cs.MsgSelectServerCL)
  return false;
#undef DO_
}

void MsgSelectServerCL::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet_cs.MsgSelectServerCL)
  // optional int32 server_id = 1;
  if (this->server_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->server_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:packet_cs.MsgSelectServerCL)
}

::google::protobuf::uint8* MsgSelectServerCL::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet_cs.MsgSelectServerCL)
  // optional int32 server_id = 1;
  if (this->server_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->server_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:packet_cs.MsgSelectServerCL)
  return target;
}

int MsgSelectServerCL::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:packet_cs.MsgSelectServerCL)
  int total_size = 0;

  // optional int32 server_id = 1;
  if (this->server_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->server_id());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgSelectServerCL::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet_cs.MsgSelectServerCL)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgSelectServerCL* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgSelectServerCL>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet_cs.MsgSelectServerCL)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet_cs.MsgSelectServerCL)
    MergeFrom(*source);
  }
}

void MsgSelectServerCL::MergeFrom(const MsgSelectServerCL& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet_cs.MsgSelectServerCL)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.server_id() != 0) {
    set_server_id(from.server_id());
  }
}

void MsgSelectServerCL::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet_cs.MsgSelectServerCL)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgSelectServerCL::CopyFrom(const MsgSelectServerCL& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet_cs.MsgSelectServerCL)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgSelectServerCL::IsInitialized() const {

  return true;
}

void MsgSelectServerCL::Swap(MsgSelectServerCL* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgSelectServerCL::InternalSwap(MsgSelectServerCL* other) {
  std::swap(server_id_, other->server_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgSelectServerCL::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgSelectServerCL_descriptor_;
  metadata.reflection = MsgSelectServerCL_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgSelectServerCL

// optional int32 server_id = 1;
void MsgSelectServerCL::clear_server_id() {
  server_id_ = 0;
}
 ::google::protobuf::int32 MsgSelectServerCL::server_id() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgSelectServerCL.server_id)
  return server_id_;
}
 void MsgSelectServerCL::set_server_id(::google::protobuf::int32 value) {
  
  server_id_ = value;
  // @@protoc_insertion_point(field_set:packet_cs.MsgSelectServerCL.server_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgSeclectServerResultLC::kResultFieldNumber;
const int MsgSeclectServerResultLC::kGateIpFieldNumber;
const int MsgSeclectServerResultLC::kGatePortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgSeclectServerResultLC::MsgSeclectServerResultLC()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet_cs.MsgSeclectServerResultLC)
}

void MsgSeclectServerResultLC::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgSeclectServerResultLC::MsgSeclectServerResultLC(const MsgSeclectServerResultLC& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:packet_cs.MsgSeclectServerResultLC)
}

void MsgSeclectServerResultLC::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  result_ = 0;
  gate_ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  gate_port_ = 0;
}

MsgSeclectServerResultLC::~MsgSeclectServerResultLC() {
  // @@protoc_insertion_point(destructor:packet_cs.MsgSeclectServerResultLC)
  SharedDtor();
}

void MsgSeclectServerResultLC::SharedDtor() {
  gate_ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MsgSeclectServerResultLC::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgSeclectServerResultLC::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgSeclectServerResultLC_descriptor_;
}

const MsgSeclectServerResultLC& MsgSeclectServerResultLC::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_client_5fserver_2eproto();
  return *default_instance_;
}

MsgSeclectServerResultLC* MsgSeclectServerResultLC::default_instance_ = NULL;

MsgSeclectServerResultLC* MsgSeclectServerResultLC::New(::google::protobuf::Arena* arena) const {
  MsgSeclectServerResultLC* n = new MsgSeclectServerResultLC;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgSeclectServerResultLC::Clear() {
// @@protoc_insertion_point(message_clear_start:packet_cs.MsgSeclectServerResultLC)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MsgSeclectServerResultLC, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MsgSeclectServerResultLC*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(result_, gate_port_);
  gate_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool MsgSeclectServerResultLC::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet_cs.MsgSeclectServerResultLC)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 result = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_gate_ip;
        break;
      }

      // optional string gate_ip = 2;
      case 2: {
        if (tag == 18) {
         parse_gate_ip:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gate_ip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->gate_ip().data(), this->gate_ip().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.MsgSeclectServerResultLC.gate_ip"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_gate_port;
        break;
      }

      // optional int32 gate_port = 3;
      case 3: {
        if (tag == 24) {
         parse_gate_port:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gate_port_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:packet_cs.MsgSeclectServerResultLC)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet_cs.MsgSeclectServerResultLC)
  return false;
#undef DO_
}

void MsgSeclectServerResultLC::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet_cs.MsgSeclectServerResultLC)
  // optional int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // optional string gate_ip = 2;
  if (this->gate_ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gate_ip().data(), this->gate_ip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgSeclectServerResultLC.gate_ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->gate_ip(), output);
  }

  // optional int32 gate_port = 3;
  if (this->gate_port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->gate_port(), output);
  }

  // @@protoc_insertion_point(serialize_end:packet_cs.MsgSeclectServerResultLC)
}

::google::protobuf::uint8* MsgSeclectServerResultLC::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet_cs.MsgSeclectServerResultLC)
  // optional int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // optional string gate_ip = 2;
  if (this->gate_ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gate_ip().data(), this->gate_ip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.MsgSeclectServerResultLC.gate_ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->gate_ip(), target);
  }

  // optional int32 gate_port = 3;
  if (this->gate_port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->gate_port(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:packet_cs.MsgSeclectServerResultLC)
  return target;
}

int MsgSeclectServerResultLC::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:packet_cs.MsgSeclectServerResultLC)
  int total_size = 0;

  // optional int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  // optional string gate_ip = 2;
  if (this->gate_ip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->gate_ip());
  }

  // optional int32 gate_port = 3;
  if (this->gate_port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->gate_port());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgSeclectServerResultLC::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet_cs.MsgSeclectServerResultLC)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgSeclectServerResultLC* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgSeclectServerResultLC>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet_cs.MsgSeclectServerResultLC)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet_cs.MsgSeclectServerResultLC)
    MergeFrom(*source);
  }
}

void MsgSeclectServerResultLC::MergeFrom(const MsgSeclectServerResultLC& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet_cs.MsgSeclectServerResultLC)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
  if (from.gate_ip().size() > 0) {

    gate_ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gate_ip_);
  }
  if (from.gate_port() != 0) {
    set_gate_port(from.gate_port());
  }
}

void MsgSeclectServerResultLC::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet_cs.MsgSeclectServerResultLC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgSeclectServerResultLC::CopyFrom(const MsgSeclectServerResultLC& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet_cs.MsgSeclectServerResultLC)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgSeclectServerResultLC::IsInitialized() const {

  return true;
}

void MsgSeclectServerResultLC::Swap(MsgSeclectServerResultLC* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgSeclectServerResultLC::InternalSwap(MsgSeclectServerResultLC* other) {
  std::swap(result_, other->result_);
  gate_ip_.Swap(&other->gate_ip_);
  std::swap(gate_port_, other->gate_port_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgSeclectServerResultLC::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgSeclectServerResultLC_descriptor_;
  metadata.reflection = MsgSeclectServerResultLC_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgSeclectServerResultLC

// optional int32 result = 1;
void MsgSeclectServerResultLC::clear_result() {
  result_ = 0;
}
 ::google::protobuf::int32 MsgSeclectServerResultLC::result() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgSeclectServerResultLC.result)
  return result_;
}
 void MsgSeclectServerResultLC::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:packet_cs.MsgSeclectServerResultLC.result)
}

// optional string gate_ip = 2;
void MsgSeclectServerResultLC::clear_gate_ip() {
  gate_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MsgSeclectServerResultLC::gate_ip() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgSeclectServerResultLC.gate_ip)
  return gate_ip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgSeclectServerResultLC::set_gate_ip(const ::std::string& value) {
  
  gate_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet_cs.MsgSeclectServerResultLC.gate_ip)
}
 void MsgSeclectServerResultLC::set_gate_ip(const char* value) {
  
  gate_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet_cs.MsgSeclectServerResultLC.gate_ip)
}
 void MsgSeclectServerResultLC::set_gate_ip(const char* value, size_t size) {
  
  gate_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet_cs.MsgSeclectServerResultLC.gate_ip)
}
 ::std::string* MsgSeclectServerResultLC::mutable_gate_ip() {
  
  // @@protoc_insertion_point(field_mutable:packet_cs.MsgSeclectServerResultLC.gate_ip)
  return gate_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MsgSeclectServerResultLC::release_gate_ip() {
  // @@protoc_insertion_point(field_release:packet_cs.MsgSeclectServerResultLC.gate_ip)
  
  return gate_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MsgSeclectServerResultLC::set_allocated_gate_ip(::std::string* gate_ip) {
  if (gate_ip != NULL) {
    
  } else {
    
  }
  gate_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gate_ip);
  // @@protoc_insertion_point(field_set_allocated:packet_cs.MsgSeclectServerResultLC.gate_ip)
}

// optional int32 gate_port = 3;
void MsgSeclectServerResultLC::clear_gate_port() {
  gate_port_ = 0;
}
 ::google::protobuf::int32 MsgSeclectServerResultLC::gate_port() const {
  // @@protoc_insertion_point(field_get:packet_cs.MsgSeclectServerResultLC.gate_port)
  return gate_port_;
}
 void MsgSeclectServerResultLC::set_gate_port(::google::protobuf::int32 value) {
  
  gate_port_ = value;
  // @@protoc_insertion_point(field_set:packet_cs.MsgSeclectServerResultLC.gate_port)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgQuitLoginCL::MsgQuitLoginCL()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet_cs.MsgQuitLoginCL)
}

void MsgQuitLoginCL::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MsgQuitLoginCL::MsgQuitLoginCL(const MsgQuitLoginCL& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:packet_cs.MsgQuitLoginCL)
}

void MsgQuitLoginCL::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

MsgQuitLoginCL::~MsgQuitLoginCL() {
  // @@protoc_insertion_point(destructor:packet_cs.MsgQuitLoginCL)
  SharedDtor();
}

void MsgQuitLoginCL::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgQuitLoginCL::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgQuitLoginCL::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgQuitLoginCL_descriptor_;
}

const MsgQuitLoginCL& MsgQuitLoginCL::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_client_5fserver_2eproto();
  return *default_instance_;
}

MsgQuitLoginCL* MsgQuitLoginCL::default_instance_ = NULL;

MsgQuitLoginCL* MsgQuitLoginCL::New(::google::protobuf::Arena* arena) const {
  MsgQuitLoginCL* n = new MsgQuitLoginCL;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MsgQuitLoginCL::Clear() {
// @@protoc_insertion_point(message_clear_start:packet_cs.MsgQuitLoginCL)
}

bool MsgQuitLoginCL::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet_cs.MsgQuitLoginCL)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:packet_cs.MsgQuitLoginCL)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet_cs.MsgQuitLoginCL)
  return false;
#undef DO_
}

void MsgQuitLoginCL::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet_cs.MsgQuitLoginCL)
  // @@protoc_insertion_point(serialize_end:packet_cs.MsgQuitLoginCL)
}

::google::protobuf::uint8* MsgQuitLoginCL::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet_cs.MsgQuitLoginCL)
  // @@protoc_insertion_point(serialize_to_array_end:packet_cs.MsgQuitLoginCL)
  return target;
}

int MsgQuitLoginCL::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:packet_cs.MsgQuitLoginCL)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgQuitLoginCL::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet_cs.MsgQuitLoginCL)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MsgQuitLoginCL* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgQuitLoginCL>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet_cs.MsgQuitLoginCL)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet_cs.MsgQuitLoginCL)
    MergeFrom(*source);
  }
}

void MsgQuitLoginCL::MergeFrom(const MsgQuitLoginCL& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet_cs.MsgQuitLoginCL)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void MsgQuitLoginCL::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet_cs.MsgQuitLoginCL)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgQuitLoginCL::CopyFrom(const MsgQuitLoginCL& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet_cs.MsgQuitLoginCL)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgQuitLoginCL::IsInitialized() const {

  return true;
}

void MsgQuitLoginCL::Swap(MsgQuitLoginCL* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgQuitLoginCL::InternalSwap(MsgQuitLoginCL* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MsgQuitLoginCL::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgQuitLoginCL_descriptor_;
  metadata.reflection = MsgQuitLoginCL_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MsgQuitLoginCL

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PktGameLoginReq::kAccountNameFieldNumber;
const int PktGameLoginReq::kSessionKeyFieldNumber;
const int PktGameLoginReq::kIpAddressFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PktGameLoginReq::PktGameLoginReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet_cs.PktGameLoginReq)
}

void PktGameLoginReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PktGameLoginReq::PktGameLoginReq(const PktGameLoginReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:packet_cs.PktGameLoginReq)
}

void PktGameLoginReq::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  account_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  session_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ip_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PktGameLoginReq::~PktGameLoginReq() {
  // @@protoc_insertion_point(destructor:packet_cs.PktGameLoginReq)
  SharedDtor();
}

void PktGameLoginReq::SharedDtor() {
  account_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  session_key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ip_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PktGameLoginReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PktGameLoginReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PktGameLoginReq_descriptor_;
}

const PktGameLoginReq& PktGameLoginReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_client_5fserver_2eproto();
  return *default_instance_;
}

PktGameLoginReq* PktGameLoginReq::default_instance_ = NULL;

PktGameLoginReq* PktGameLoginReq::New(::google::protobuf::Arena* arena) const {
  PktGameLoginReq* n = new PktGameLoginReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PktGameLoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:packet_cs.PktGameLoginReq)
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  session_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ip_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool PktGameLoginReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet_cs.PktGameLoginReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string account_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account_name().data(), this->account_name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.PktGameLoginReq.account_name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_session_key;
        break;
      }

      // optional string session_key = 2;
      case 2: {
        if (tag == 18) {
         parse_session_key:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->session_key().data(), this->session_key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.PktGameLoginReq.session_key"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_ip_address;
        break;
      }

      // optional string ip_address = 3;
      case 3: {
        if (tag == 26) {
         parse_ip_address:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ip_address().data(), this->ip_address().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.PktGameLoginReq.ip_address"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:packet_cs.PktGameLoginReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet_cs.PktGameLoginReq)
  return false;
#undef DO_
}

void PktGameLoginReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet_cs.PktGameLoginReq)
  // optional string account_name = 1;
  if (this->account_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account_name().data(), this->account_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktGameLoginReq.account_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->account_name(), output);
  }

  // optional string session_key = 2;
  if (this->session_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->session_key().data(), this->session_key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktGameLoginReq.session_key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->session_key(), output);
  }

  // optional string ip_address = 3;
  if (this->ip_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip_address().data(), this->ip_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktGameLoginReq.ip_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->ip_address(), output);
  }

  // @@protoc_insertion_point(serialize_end:packet_cs.PktGameLoginReq)
}

::google::protobuf::uint8* PktGameLoginReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet_cs.PktGameLoginReq)
  // optional string account_name = 1;
  if (this->account_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account_name().data(), this->account_name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktGameLoginReq.account_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->account_name(), target);
  }

  // optional string session_key = 2;
  if (this->session_key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->session_key().data(), this->session_key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktGameLoginReq.session_key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->session_key(), target);
  }

  // optional string ip_address = 3;
  if (this->ip_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip_address().data(), this->ip_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktGameLoginReq.ip_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->ip_address(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:packet_cs.PktGameLoginReq)
  return target;
}

int PktGameLoginReq::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:packet_cs.PktGameLoginReq)
  int total_size = 0;

  // optional string account_name = 1;
  if (this->account_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account_name());
  }

  // optional string session_key = 2;
  if (this->session_key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->session_key());
  }

  // optional string ip_address = 3;
  if (this->ip_address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ip_address());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PktGameLoginReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet_cs.PktGameLoginReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PktGameLoginReq* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PktGameLoginReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet_cs.PktGameLoginReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet_cs.PktGameLoginReq)
    MergeFrom(*source);
  }
}

void PktGameLoginReq::MergeFrom(const PktGameLoginReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet_cs.PktGameLoginReq)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.account_name().size() > 0) {

    account_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_name_);
  }
  if (from.session_key().size() > 0) {

    session_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.session_key_);
  }
  if (from.ip_address().size() > 0) {

    ip_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_address_);
  }
}

void PktGameLoginReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet_cs.PktGameLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PktGameLoginReq::CopyFrom(const PktGameLoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet_cs.PktGameLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PktGameLoginReq::IsInitialized() const {

  return true;
}

void PktGameLoginReq::Swap(PktGameLoginReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PktGameLoginReq::InternalSwap(PktGameLoginReq* other) {
  account_name_.Swap(&other->account_name_);
  session_key_.Swap(&other->session_key_);
  ip_address_.Swap(&other->ip_address_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PktGameLoginReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PktGameLoginReq_descriptor_;
  metadata.reflection = PktGameLoginReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PktGameLoginReq

// optional string account_name = 1;
void PktGameLoginReq::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PktGameLoginReq::account_name() const {
  // @@protoc_insertion_point(field_get:packet_cs.PktGameLoginReq.account_name)
  return account_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PktGameLoginReq::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet_cs.PktGameLoginReq.account_name)
}
 void PktGameLoginReq::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet_cs.PktGameLoginReq.account_name)
}
 void PktGameLoginReq::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet_cs.PktGameLoginReq.account_name)
}
 ::std::string* PktGameLoginReq::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:packet_cs.PktGameLoginReq.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PktGameLoginReq::release_account_name() {
  // @@protoc_insertion_point(field_release:packet_cs.PktGameLoginReq.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PktGameLoginReq::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:packet_cs.PktGameLoginReq.account_name)
}

// optional string session_key = 2;
void PktGameLoginReq::clear_session_key() {
  session_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PktGameLoginReq::session_key() const {
  // @@protoc_insertion_point(field_get:packet_cs.PktGameLoginReq.session_key)
  return session_key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PktGameLoginReq::set_session_key(const ::std::string& value) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet_cs.PktGameLoginReq.session_key)
}
 void PktGameLoginReq::set_session_key(const char* value) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet_cs.PktGameLoginReq.session_key)
}
 void PktGameLoginReq::set_session_key(const char* value, size_t size) {
  
  session_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet_cs.PktGameLoginReq.session_key)
}
 ::std::string* PktGameLoginReq::mutable_session_key() {
  
  // @@protoc_insertion_point(field_mutable:packet_cs.PktGameLoginReq.session_key)
  return session_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PktGameLoginReq::release_session_key() {
  // @@protoc_insertion_point(field_release:packet_cs.PktGameLoginReq.session_key)
  
  return session_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PktGameLoginReq::set_allocated_session_key(::std::string* session_key) {
  if (session_key != NULL) {
    
  } else {
    
  }
  session_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_key);
  // @@protoc_insertion_point(field_set_allocated:packet_cs.PktGameLoginReq.session_key)
}

// optional string ip_address = 3;
void PktGameLoginReq::clear_ip_address() {
  ip_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PktGameLoginReq::ip_address() const {
  // @@protoc_insertion_point(field_get:packet_cs.PktGameLoginReq.ip_address)
  return ip_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PktGameLoginReq::set_ip_address(const ::std::string& value) {
  
  ip_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:packet_cs.PktGameLoginReq.ip_address)
}
 void PktGameLoginReq::set_ip_address(const char* value) {
  
  ip_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:packet_cs.PktGameLoginReq.ip_address)
}
 void PktGameLoginReq::set_ip_address(const char* value, size_t size) {
  
  ip_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:packet_cs.PktGameLoginReq.ip_address)
}
 ::std::string* PktGameLoginReq::mutable_ip_address() {
  
  // @@protoc_insertion_point(field_mutable:packet_cs.PktGameLoginReq.ip_address)
  return ip_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PktGameLoginReq::release_ip_address() {
  // @@protoc_insertion_point(field_release:packet_cs.PktGameLoginReq.ip_address)
  
  return ip_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PktGameLoginReq::set_allocated_ip_address(::std::string* ip_address) {
  if (ip_address != NULL) {
    
  } else {
    
  }
  ip_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip_address);
  // @@protoc_insertion_point(field_set_allocated:packet_cs.PktGameLoginReq.ip_address)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PktRoleListAck::kRoleNameListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PktRoleListAck::PktRoleListAck()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:packet_cs.PktRoleListAck)
}

void PktRoleListAck::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PktRoleListAck::PktRoleListAck(const PktRoleListAck& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:packet_cs.PktRoleListAck)
}

void PktRoleListAck::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
}

PktRoleListAck::~PktRoleListAck() {
  // @@protoc_insertion_point(destructor:packet_cs.PktRoleListAck)
  SharedDtor();
}

void PktRoleListAck::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PktRoleListAck::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PktRoleListAck::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PktRoleListAck_descriptor_;
}

const PktRoleListAck& PktRoleListAck::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_client_5fserver_2eproto();
  return *default_instance_;
}

PktRoleListAck* PktRoleListAck::default_instance_ = NULL;

PktRoleListAck* PktRoleListAck::New(::google::protobuf::Arena* arena) const {
  PktRoleListAck* n = new PktRoleListAck;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PktRoleListAck::Clear() {
// @@protoc_insertion_point(message_clear_start:packet_cs.PktRoleListAck)
  role_name_list_.Clear();
}

bool PktRoleListAck::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:packet_cs.PktRoleListAck)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string role_name_list = 1;
      case 1: {
        if (tag == 10) {
         parse_role_name_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_role_name_list()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->role_name_list(this->role_name_list_size() - 1).data(),
            this->role_name_list(this->role_name_list_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "packet_cs.PktRoleListAck.role_name_list"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_role_name_list;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:packet_cs.PktRoleListAck)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:packet_cs.PktRoleListAck)
  return false;
#undef DO_
}

void PktRoleListAck::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:packet_cs.PktRoleListAck)
  // repeated string role_name_list = 1;
  for (int i = 0; i < this->role_name_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->role_name_list(i).data(), this->role_name_list(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktRoleListAck.role_name_list");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->role_name_list(i), output);
  }

  // @@protoc_insertion_point(serialize_end:packet_cs.PktRoleListAck)
}

::google::protobuf::uint8* PktRoleListAck::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:packet_cs.PktRoleListAck)
  // repeated string role_name_list = 1;
  for (int i = 0; i < this->role_name_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->role_name_list(i).data(), this->role_name_list(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "packet_cs.PktRoleListAck.role_name_list");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->role_name_list(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:packet_cs.PktRoleListAck)
  return target;
}

int PktRoleListAck::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:packet_cs.PktRoleListAck)
  int total_size = 0;

  // repeated string role_name_list = 1;
  total_size += 1 * this->role_name_list_size();
  for (int i = 0; i < this->role_name_list_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->role_name_list(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PktRoleListAck::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:packet_cs.PktRoleListAck)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PktRoleListAck* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PktRoleListAck>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:packet_cs.PktRoleListAck)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:packet_cs.PktRoleListAck)
    MergeFrom(*source);
  }
}

void PktRoleListAck::MergeFrom(const PktRoleListAck& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:packet_cs.PktRoleListAck)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  role_name_list_.MergeFrom(from.role_name_list_);
}

void PktRoleListAck::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:packet_cs.PktRoleListAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PktRoleListAck::CopyFrom(const PktRoleListAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:packet_cs.PktRoleListAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PktRoleListAck::IsInitialized() const {

  return true;
}

void PktRoleListAck::Swap(PktRoleListAck* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PktRoleListAck::InternalSwap(PktRoleListAck* other) {
  role_name_list_.UnsafeArenaSwap(&other->role_name_list_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PktRoleListAck::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PktRoleListAck_descriptor_;
  metadata.reflection = PktRoleListAck_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PktRoleListAck

// repeated string role_name_list = 1;
int PktRoleListAck::role_name_list_size() const {
  return role_name_list_.size();
}
void PktRoleListAck::clear_role_name_list() {
  role_name_list_.Clear();
}
 const ::std::string& PktRoleListAck::role_name_list(int index) const {
  // @@protoc_insertion_point(field_get:packet_cs.PktRoleListAck.role_name_list)
  return role_name_list_.Get(index);
}
 ::std::string* PktRoleListAck::mutable_role_name_list(int index) {
  // @@protoc_insertion_point(field_mutable:packet_cs.PktRoleListAck.role_name_list)
  return role_name_list_.Mutable(index);
}
 void PktRoleListAck::set_role_name_list(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:packet_cs.PktRoleListAck.role_name_list)
  role_name_list_.Mutable(index)->assign(value);
}
 void PktRoleListAck::set_role_name_list(int index, const char* value) {
  role_name_list_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:packet_cs.PktRoleListAck.role_name_list)
}
 void PktRoleListAck::set_role_name_list(int index, const char* value, size_t size) {
  role_name_list_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:packet_cs.PktRoleListAck.role_name_list)
}
 ::std::string* PktRoleListAck::add_role_name_list() {
  // @@protoc_insertion_point(field_add_mutable:packet_cs.PktRoleListAck.role_name_list)
  return role_name_list_.Add();
}
 void PktRoleListAck::add_role_name_list(const ::std::string& value) {
  role_name_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:packet_cs.PktRoleListAck.role_name_list)
}
 void PktRoleListAck::add_role_name_list(const char* value) {
  role_name_list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:packet_cs.PktRoleListAck.role_name_list)
}
 void PktRoleListAck::add_role_name_list(const char* value, size_t size) {
  role_name_list_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:packet_cs.PktRoleListAck.role_name_list)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
PktRoleListAck::role_name_list() const {
  // @@protoc_insertion_point(field_list:packet_cs.PktRoleListAck.role_name_list)
  return role_name_list_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
PktRoleListAck::mutable_role_name_list() {
  // @@protoc_insertion_point(field_mutable_list:packet_cs.PktRoleListAck.role_name_list)
  return &role_name_list_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace packet_cs

// @@protoc_insertion_point(global_scope)
